name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # jalan otomatis tiap hari jam 00:00 UTC
  workflow_dispatch: {} # bisa dipicu manual dari tab Actions
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake game SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/dark-castle-snake.svg?color_snake=%23B8860B&color_dots=%232b1055,%232b1055,%234b0082,%237b2ff7,%238b0000

      - name: Push output to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}